@apiKey = your_server_api_key


### Start a new thread
POST http://127.0.0.1:4069/start-thread
Content-Type: application/json
X-API-Key: {{apiKey}}


#### Chat with the chatbot in a specified thread.
POST http://127.0.0.1:4069/chat
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "threadId": "yourThreadId",
    "message": "yourMessage"
}